CREATE TABLE IF NOT EXISTS llx_seven_sms_outbox
(
	ID	int(10) AUTO_INCREMENT PRIMARY KEY,
	msgid VARCHAR(255) DEFAULT NULL,
	sender VARCHAR(20) NOT NULL,
	message TEXT NOT NULL,
	recipient TEXT NOT NULL,
	status SMALLINT NOT NULL DEFAULT 1,
	source VARCHAR(255) DEFAULT NULL,
	date DATETIME DEFAULT NULL,
	type VARCHAR(10) NOT NULL
) ENGINE=innodb;
